name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci --no-audit

      - name: Install Playwright Chromium
        run: npx playwright install chromium

      - name: Run Playwright tests (Chromium Only)
        run: npx playwright test --project=chromium --reporter=html,line

      - name: Upload HTML Report (Failures Only)
        if: failure() && !cancelled()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-failure-report
          path: playwright-report/
          retention-days: 2
          compression-level: 0
